### ISSUE TITLE
Atributo volumen en un magento vanilla

### ISSUE THREAD

**Issue by manuelcanepa** [andreani-publico/magento-2.3#1]
El UpgradeData no permite que se corra bien el setup:upgrade porque no conoce el atributo "volumen" en una instalacion fresca de magento. Si se modifica el nombre de `app/code/DrubuNet/Andreani/Setup/InstallData.php.nouse` a `app/code/DrubuNet/Andreani/Setup/InstallData.php` se soluciona.

El error que arroja es: `Upgrading data... Attribute with ID: "volumen" does not exist`

**Comment by nmarquezdrubu** [comment]
Gracias @manuelcanepa, ya lo corregimos y en breve estaremos subiendo el fix.
Saludos!
